export default interface AccountCustom {

  account_id: string,
  name: string,
  email: string,
  owner: string,
  created_at: string,
  users: string,
  phone_numbers: string,
  source: string,
  status: string,
  avatar_url: string,
  created_by: string,
  phone: string,
  last_edited_at: string,
  last_edited_by: string,
  time_zone: string,
  permission: string,
  twilio_account_sid: string,
  twilio_call_token: string,
  twilio_token: string,
  mailing_street: string,
  mailing_unit: string,
  mailing_city: string,
  mailing_state: string,
  mailing_zip: string,
  billing_street: string,
  billing_unit: string,
  billing_city: string,
  billing_state: string,
  billing_zip: string,
  same_address: boolean,

  slack_url: string,
  slack_active: boolean
}
